export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: false,
  theme: {
    extend: {
      colors: {
        background: 'var(--bg)',
        surface: 'var(--surface)',
        border: 'var(--border)',
        foreground: 'var(--text)',
        muted: 'var(--muted)',
        accent: 'var(--accent)',
        'accent-soft': 'var(--accent-soft)',
        success: '#059669',
        warning: '#d97706',
        danger: '#dc2626',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '9px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
      },
      boxShadow: {
        xs: '0 1px 2px rgba(0,0,0,.05)',
        sm: '0 1px 3px rgba(0,0,0,.07)',
        md: '0 4px 14px rgba(0,0,0,.08)',
        lg: '0 10px 32px rgba(0,0,0,.1)',
        card: '0 1px 4px rgba(0,0,0,.06)',
        'card-hover': '0 6px 20px rgba(0,0,0,.1)',
        teal: '0 4px 14px rgba(13,148,136,.25)',
        amber: '0 4px 14px rgba(217,119,6,.2)',
        input: '0 0 0 3px rgba(13,148,136,.15)',
      },
      keyframes: {
        'fade-up': { from:{opacity:'0',transform:'translateY(12px)'}, to:{opacity:'1',transform:'translateY(0)'} },
        'fade-in': { from:{opacity:'0'}, to:{opacity:'1'} },
        'scale-in': { from:{opacity:'0',transform:'translate(-50%,-48%) scale(.96)'}, to:{opacity:'1',transform:'translate(-50%,-50%) scale(1)'} },
        'slide-right': { from:{opacity:'0',transform:'translateX(16px)'}, to:{opacity:'1',transform:'translateX(0)'} },
        'shimmer': { from:{backgroundPosition:'200% 0'}, to:{backgroundPosition:'-200% 0'} },
        'float': { '0%,100%':{transform:'translateY(0)'}, '50%':{transform:'translateY(-6px)'} },
        'pulse-ring': { '0%':{transform:'scale(1)',opacity:'1'}, '100%':{transform:'scale(1.6)',opacity:'0'} },
        'spin-slow': { from:{transform:'rotate(0deg)'}, to:{transform:'rotate(360deg)'} },
        'page-in': { from:{opacity:'0',transform:'translateY(6px)'}, to:{opacity:'1',transform:'translateY(0)'} },
      },
      animation: {
        'fade-up': 'fade-up 0.4s cubic-bezier(.16,1,.3,1)',
        'fade-in': 'fade-in 0.3s ease',
        'scale-in': 'scale-in 0.25s cubic-bezier(.16,1,.3,1)',
        'slide-right': 'slide-right 0.25s cubic-bezier(.16,1,.3,1)',
        'shimmer': 'shimmer 1.8s linear infinite',
        'float': 'float 4s ease-in-out infinite',
        'pulse-ring': 'pulse-ring 1.8s cubic-bezier(0,0,.2,1) infinite',
        'spin-slow': 'spin-slow 10s linear infinite',
        'page-in': 'page-in 0.3s cubic-bezier(.16,1,.3,1)',
      },
    },
  },
  plugins: [],
}
