import type { ReactNode, ButtonHTMLAttributes, InputHTMLAttributes } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { X, BookOpen, Check, Clock, ArrowUpDown } from 'lucide-react'
import { useState } from 'react'
export function Button({className='',variant='primary',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:string}){return <button className={`btn btn-${variant} ${className}`} {...props}/>}
export function Input({className='',...props}:InputHTMLAttributes<HTMLInputElement>){return <input className={`input ${className}`} {...props}/>}
export function Card({children,className=''}:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function Avatar({name,size=''}:{name:string;size?:string}){return <span className={`avatar ${size}`} aria-label={name}>{name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
export function StatusBadge({status}:{status:string}){return <Badge tone={['approved','trusted','valid'].includes(status)?'success':status==='rejected'?'danger':'warning'}>{status==='approved'?<Check size={12}/>:<Clock size={12}/>} {status==='approved'?'Reviewed':status}</Badge>}
export function Empty({title,hint,children}:{title:string;hint?:string;children?:ReactNode}){return <div className="empty"><BookOpen size={32}/><h3>{title}</h3><p>{hint}</p>{children}</div>}
export function Skeleton(){return <div className="notes-grid" aria-label="Loading notes">{[1,2,3,4,5,6].map(n=><div className="card skeleton" key={n}/>)}</div>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal" aria-describedby={undefined}><Dialog.Title>{title}</Dialog.Title><Dialog.Close className="icon-btn modal-close" aria-label="Close dialog"><X size={19}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export type TableRow={id:string;[key:string]:ReactNode}
export function Table({columns,rows}:{columns:{key:string;label:string}[];rows:TableRow[]}){const [search,setSearch]=useState('');const [sort,setSort]=useState('');const [asc,setAsc]=useState(true);const [page,setPage]=useState(0);const filtered=rows.filter(r=>Object.values(r).some(v=>typeof v==='string'&&v.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''))*(asc?1:-1));return <><div className="table-toolbar"><Input aria-label="Search table" placeholder="Search records…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}}/><span className="muted">{filtered.length} records</span></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c.key}><button onClick={()=>{setSort(c.key);setAsc(!asc)}}>{c.label}<ArrowUpDown size={12}/></button></th>)}</tr></thead><tbody>{filtered.slice(page*6,page*6+6).map(r=><tr key={r.id}>{columns.map(c=><td key={c.key}>{r[c.key]}</td>)}</tr>)}</tbody></table></div>{!filtered.length&&<Empty title="No matching records" hint="Try another search."/>}<div className="pagination"><span>Page {page+1} of {Math.max(1,Math.ceil(filtered.length/6))}</span><Button variant="secondary" disabled={!page} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="secondary" disabled={(page+1)*6>=filtered.length} onClick={()=>setPage(page+1)}>Next</Button></div></>}
