import type { Note, StudyClass, Report, ModeratorRequest } from '../lib/auth'

export const INITIAL_CLASSES: StudyClass[] = [
  { id: 'cs201', name: 'CS 201', subject: 'Computer Science', description: 'Data Structures & Algorithms in C++ and Java', noteCount: 28 },
  { id: 'ma202', name: 'MA 202', subject: 'Mathematics', description: 'Multivariable Calculus & Linear Algebra', noteCount: 19 },
  { id: 'ph101', name: 'PH 101', subject: 'Physics', description: 'Classical Mechanics & Wave Dynamics', noteCount: 16 },
  { id: 'cs301', name: 'CS 301', subject: 'Computer Science', description: 'Relational Database Management Systems & SQL', noteCount: 14 },
  { id: 'bio110', name: 'BIO 110', subject: 'Biology', description: 'Cellular Biology, Genetics & Evolution', noteCount: 11 },
  { id: 'econ101', name: 'ECON 101', subject: 'Economics', description: 'Principles of Microeconomics & Market Dynamics', noteCount: 9 },
]

export const INITIAL_NOTES: Note[] = [
  {
    id: '1',
    title: 'Data Structures & Algorithmic Complexity: Master Guide',
    description: 'Comprehensive lecture synthesis covering balanced binary search trees (AVL & Red-Black), graph traversal (DFS/BFS, Dijkstra), amortized complexity, and priority heaps.',
    subject: 'Computer Science',
    classId: 'cs201',
    tags: ['Algorithms', 'Trees', 'Graphs', 'Big-O', 'Exam Prep'],
    fileName: 'cs201_complete_trees_graphs.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'usr_aisha',
    uploadedByName: 'Aisha Chen',
    status: 'approved',
    trusted: true,
    downloads: 342,
    pages: 28,
    color: 'lavender',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    summary: 'This note synthesizes foundational computer science data structures with rigorous Big-O time and space complexity proofs. Key emphasis is placed on balancing invariant maintenance in self-balancing binary search trees and shortest-path graph optimization.',
    keyConcepts: [
      'Self-balancing binary trees maintain O(log n) worst-case search by executing constant-time tree rotations.',
      'Dijkstra algorithm operates in O((V + E) log V) time when supported by a min-indexed binary heap.',
      'Amortized analysis using the accounting method demonstrates that dynamic array resizings cost O(1) on average.',
    ],
    flashcards: [
      { q: 'What is the maximum height of a Red-Black tree with N internal nodes?', a: '2 * log2(N + 1).' },
      { q: 'When does Dijkstra algorithm fail?', a: 'When graph edges carry negative weights (Bellman-Ford is needed instead).' },
      { q: 'What is the amortized cost of inserting into an array list?', a: 'O(1) amortized, despite occasional O(n) array copy overhead.' },
    ],
  },
  {
    id: '2',
    title: 'Linear Algebra & Eigen-Decomposition Intuition',
    description: 'Visual geometric foundations of matrix transformations, eigenvectors, eigenvalues, singular value decomposition (SVD), and least squares approximations.',
    subject: 'Mathematics',
    classId: 'ma202',
    tags: ['Matrices', 'Eigenvalues', 'SVD', 'Midterm Revision'],
    fileName: 'ma202_linear_algebra_visuals.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'usr_diego',
    uploadedByName: 'Diego Ramirez',
    status: 'approved',
    trusted: false,
    downloads: 215,
    pages: 22,
    color: 'peach',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    summary: 'A geometric review of vector transformations focusing on invariant directions (eigenvectors). Unpacks the fundamental theorem of linear algebra, row space orthogonality, and SVD decomposition for dimensionality reduction.',
    keyConcepts: [
      'An eigenvector satisfies Av = λv: the transformation only scales the vector without rotating its direction.',
      'The row space and null space of any matrix A are orthogonal complements in R^n.',
      'SVD factorizes any matrix A into U * Σ * V^T, allowing optimal low-rank matrix approximations.',
    ],
    flashcards: [
      { q: 'What does a zero eigenvalue imply about matrix A?', a: 'Matrix A is singular and non-invertible; its determinant equals zero.' },
      { q: 'What are the singular values of matrix A?', a: 'The square roots of the eigenvalues of A^T * A.' },
    ],
  },
  {
    id: '3',
    title: 'Electromagnetism & Maxwell’s Equations in Integral Form',
    description: 'Step-by-step derivation of Gauss’s Law, Faraday’s Law, Ampère-Maxwell Law, and Poynting vector radiation flux with worked problem sets.',
    subject: 'Physics',
    classId: 'ph101',
    tags: ['Electromagnetism', 'Flux', 'Fields', 'Maxwell'],
    fileName: 'ph101_maxwells_equations.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'usr_aisha',
    uploadedByName: 'Aisha Chen',
    status: 'approved',
    trusted: true,
    downloads: 189,
    pages: 34,
    color: 'mint',
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
    summary: 'Unifies electrostatics and electrodynamics into Maxwell’s four fundamental field equations. Analyzes symmetric charge distributions and induced electromagnetic wave propagation in vacuum.',
    keyConcepts: [
      'Gauss’s law equates electric flux through a closed surface to the enclosed charge divided by permittivity.',
      'Faraday’s law of induction indicates that a time-varying magnetic flux induces an electromotive force (EMF).',
      'The displacement current term in Ampère’s law resolves charge conservation dilemmas during capacitor charging.',
    ],
    flashcards: [
      { q: 'Why is the magnetic flux through any closed Gaussian surface always zero?', a: 'Because magnetic monopoles have not been observed in nature.' },
      { q: 'What physical quantity does the Poynting Vector represent?', a: 'Direction and rate of electromagnetic energy flux per unit area.' },
    ],
  },
  {
    id: '4',
    title: 'Relational Normalization: 1NF through BCNF with Tradeoffs',
    description: 'Clear breakdown of functional dependencies, Armstrong’s axioms, lossless joins, dependency preservation, and decomposition algorithms.',
    subject: 'Computer Science',
    classId: 'cs301',
    tags: ['Database', 'SQL', 'Normalization', 'BCNF'],
    fileName: 'cs301_database_normalization.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'usr_aisha',
    uploadedByName: 'Aisha Chen',
    status: 'approved',
    trusted: true,
    downloads: 164,
    pages: 18,
    color: 'blue',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    summary: 'Rigorous approach to database normalization to eradicate update, insert, and deletion anomalies while identifying functional dependency preservation boundaries.',
    keyConcepts: [
      '3NF allows non-prime attributes to be functionally dependent on candidate keys or superkeys.',
      'BCNF strictly requires every non-trivial functional dependency X -> Y to have X as a superkey.',
      'Decompositions into BCNF always ensure lossless join but may not preserve all original functional dependencies.',
    ],
    flashcards: [
      { q: 'What is the primary difference between 3NF and BCNF?', a: '3NF permits A in X -> A to be a prime attribute even if X is not a superkey; BCNF requires X to always be a superkey.' },
    ],
  },
  {
    id: '5',
    title: 'Cellular Respiration & Krebs Cycle Step-by-Step Flowchart',
    description: 'Detailed biochemical pathways from glycolysis to oxidative phosphorylation with ATP yield calculation tables and enzyme regulation mechanisms.',
    subject: 'Biology',
    classId: 'bio110',
    tags: ['Biochemistry', 'Krebs Cycle', 'ATP', 'Cell Biology'],
    fileName: 'bio110_cellular_respiration.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'usr_diego',
    uploadedByName: 'Diego Ramirez',
    status: 'pending',
    trusted: false,
    downloads: 0,
    pages: 15,
    color: 'sand',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    summary: 'A visual schematic mapping glucose oxidation across cytosolic glycolysis and mitochondrial matrix reactions. Tabulates exact stoichiometric ATP yields per NADH and FADH2.',
    keyConcepts: [
      'Glycolysis produces net 2 ATP and 2 NADH without requiring molecular oxygen.',
      'The proton gradient across the inner mitochondrial membrane powers ATP synthase via chemiosmosis.',
    ],
    flashcards: [
      { q: 'Where does the citric acid cycle occur in eukaryotic cells?', a: 'In the mitochondrial matrix.' },
    ],
  },
  {
    id: '6',
    title: 'Market Equilibrium & Consumer Surplus Formulas',
    description: 'Elasticity of demand, price ceilings/floors deadweight loss graphs, and utility maximization curves.',
    subject: 'Economics',
    classId: 'econ101',
    tags: ['Microeconomics', 'Surplus', 'Elasticity'],
    fileName: 'econ101_microeconomics_summary.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'usr_student',
    uploadedByName: 'Alex Morgan',
    status: 'pending',
    trusted: false,
    downloads: 0,
    pages: 12,
    color: 'rose',
    createdAt: new Date().toISOString(),
    summary: 'Explains welfare economics, price controls, and social surplus deadweight losses with supply and demand curves.',
    keyConcepts: [
      'Deadweight loss represents the reduction in total social surplus caused by market distortions like taxes or subsidies.',
    ],
    flashcards: [
      { q: 'What happens when price elasticity of demand is greater than 1?', a: 'Demand is elastic; percentage change in quantity exceeds percentage change in price.' },
    ],
  },
]

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep_101',
    noteId: '2',
    noteTitle: 'Linear Algebra & Eigen-Decomposition Intuition',
    reportedByName: 'Marcus Wright',
    reason: 'Page 14 equation for determinant characteristic polynomial has an inverted sign in the trace term.',
    status: 'open',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'rep_102',
    noteId: '3',
    noteTitle: 'Electromagnetism & Maxwell’s Equations in Integral Form',
    reportedByName: 'Elena Rostova',
    reason: 'Incorrect unit notation on electric permittivity constant on the reference cheat sheet.',
    status: 'open',
    createdAt: new Date(Date.now() - 28 * 3600000).toISOString(),
  },
  {
    id: 'rep_100',
    noteId: '4',
    noteTitle: 'Relational Normalization',
    reportedByName: 'David Kim',
    reason: 'Minor formatting typo on 2NF bullet points.',
    status: 'dismissed',
    createdAt: new Date(Date.now() - 72 * 3600000).toISOString(),
  },
]

export const INITIAL_MOD_REQUESTS: ModeratorRequest[] = [
  {
    id: 'req_01',
    userId: 'usr_diego',
    userName: 'Diego Ramirez',
    userEmail: 'diego@notevault.com',
    status: 'pending',
    reason: 'Graduate Teaching Assistant in Mathematics at MIT. Wanting to upload verified exam prep packages and problem set walkthroughs.',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'req_02',
    userId: 'usr_jordan',
    userName: 'Jordan Lee',
    userEmail: 'jordan.lee@stanford.edu',
    status: 'pending',
    reason: 'Head tutor for CS 201 algorithms study sessions. Looking to curate study notes and help peer review student contributions.',
    createdAt: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
]

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'aud_901',
    userName: 'Sarah Connor (Admin)',
    action: 'note.approved',
    target: 'Data Structures & Algorithmic Complexity: Master Guide',
    details: 'Verified LaTeX equations and verified attribution license. Contributor Aisha Chen awarded +1 clean upload.',
    createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: 'aud_902',
    userName: 'System (TrustEngine)',
    action: 'reputation.promoted',
    target: 'Aisha Chen (usr_aisha)',
    details: 'Achieved 5/5 consecutive clean approvals. Moderator status flipped to isTrusted=true (Auto-Publish enabled).',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'aud_903',
    userName: 'Sarah Connor (Admin)',
    action: 'report.resolved',
    target: 'Relational Normalization (rep_100)',
    details: 'Dismissed report as minor typo not violating academic integrity guidelines.',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'aud_904',
    userName: 'Sarah Connor (Admin)',
    action: 'moderator.verified',
    target: 'Diego Ramirez (usr_diego)',
    details: 'Approved moderator application as unproven contributor (trust: 0/5 required).',
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
]

export interface KafkaStreamEvent {
  eventId: string
  topic: 'note-events' | 'audit-stream' | 'reputation-stream' | 'user-events' | 'search-events'
  partition: number
  offset: number
  key: string
  payload: Record<string, any>
  timestamp: string
}

export const INITIAL_STREAM_EVENTS: KafkaStreamEvent[] = [
  {
    eventId: 'evt_kfk_8801',
    topic: 'note-events',
    partition: 1,
    offset: 4920,
    key: 'note-1',
    payload: {
      eventType: 'NOTE_UPLOADED',
      noteId: '1',
      title: 'Data Structures & Algorithmic Complexity',
      uploaderId: 'usr_aisha',
      autoPublished: true,
      trustStatus: 'TRUSTED',
    },
    timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    eventId: 'evt_kfk_8802',
    topic: 'reputation-stream',
    partition: 0,
    offset: 1204,
    key: 'usr_aisha',
    payload: {
      eventType: 'TRUST_INCREMENTED',
      userId: 'usr_aisha',
      cleanCount: 5,
      threshold: 5,
      isTrustedNow: true,
      reason: 'CLEAN_UPLOAD_APPROVED',
    },
    timestamp: new Date(Date.now() - 14 * 60000).toISOString(),
  },
  {
    eventId: 'evt_kfk_8803',
    topic: 'audit-stream',
    partition: 2,
    offset: 8301,
    key: 'admin-sarah',
    payload: {
      eventType: 'ADMIN_DECISION',
      actor: 'admin@notevault.com',
      action: 'APPROVE_NOTE',
      targetId: '1',
      trustDelta: '+1',
    },
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    eventId: 'evt_kfk_8804',
    topic: 'search-events',
    partition: 0,
    offset: 15480,
    key: 'anon-search',
    payload: {
      eventType: 'QUERY_EXECUTED',
      query: 'dijkstra binary heap priority queue',
      matchedCount: 3,
      semanticScore: 0.94,
    },
    timestamp: new Date(Date.now() - 42 * 60000).toISOString(),
  },
  {
    eventId: 'evt_kfk_8805',
    topic: 'note-events',
    partition: 1,
    offset: 4921,
    key: 'note-5',
    payload: {
      eventType: 'NOTE_PENDING_REVIEW',
      noteId: '5',
      title: 'Cellular Respiration & Krebs Cycle',
      uploaderId: 'usr_diego',
      autoPublished: false,
      trustStatus: 'UNPROVEN_MODERATOR',
    },
    timestamp: new Date(Date.now() - 65 * 60000).toISOString(),
  },
]
