import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MotionConfig } from 'framer-motion'
import { AuthProvider } from './lib/auth'
import { WorkspaceProvider } from './lib/workspace'
import AppLayout from './layouts/AppLayout'
import LandingPage from './pages/LandingPage'
import AuthPage from './pages/AuthPage'
import { DashboardPage, BrowsePage, ClassesPage } from './pages/WorkspacePages'
import SearchPage from './pages/SearchPage'
import ViewerPage from './pages/ViewerPage'
import UploadPage from './pages/UploadPage'
import AdminPage from './pages/AdminPage'
const client=new QueryClient({defaultOptions:{queries:{staleTime:30000,refetchOnWindowFocus:false}}})
export default function App(){return <QueryClientProvider client={client}><BrowserRouter><AuthProvider><WorkspaceProvider><MotionConfig reducedMotion="user"><Routes><Route path="/" element={<LandingPage/>}/><Route path="/login" element={<AuthPage/>}/><Route path="/signup" element={<AuthPage signup/>}/><Route element={<AppLayout/>}><Route path="/home" element={<DashboardPage/>}/><Route path="/notes" element={<BrowsePage/>}/><Route path="/notes/:id" element={<ViewerPage/>}/><Route path="/classes" element={<ClassesPage/>}/><Route path="/saved" element={<BrowsePage savedOnly/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/upload" element={<UploadPage/>}/><Route path="/studio" element={<Navigate to="/upload" replace/>}/><Route path="/admin" element={<AdminPage/>}/><Route path="/admin/:section" element={<AdminPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes></MotionConfig></WorkspaceProvider></AuthProvider></BrowserRouter></QueryClientProvider>}
